# Silakan jelaskan secara singkat dan jelas mengenai model final yang telah dibuat/dipilih oleh tim.

Model yang kami pilih adalah Decision Tree Classifier. Model ini dipilih karena model ini memiliki akurasi yang cukup baik dan memiliki Learning Curve yang stabil. Selain itu, model ini juga memiliki waktu komputasi yang relatif cepat jika dibandingkan 2 model lainnya, yaitu Adaptive Boosting dan Extreme Gradient Boosting. Model ini juga tidak overfitting dan underfitting. Jadi memenuhi kriteria yang kami inginkan. Fitur yang kami gunakan adalah fitur yang sudah kami pilih sebelumnya, yaitu fitur yang seacara rasionalitas dapat mempengaruhi target. Hal ini karena korelasi antar fitur dengan target yang rendah. Batasan model ini hanya digunakan untuk melakukan klasifikasi multilabel pada target industri pekerjaan yang sesuai karakteristik yang diberikan responden.

Evaluation metric yang kami gunakan adalah Accuracy, Precision, Recall, F1 Score, dan Learning Curve. Kami menggunakan metric ini karena kami ingin mengetahui seberapa baik model kami dalam melakukan klasifikasi. Dan dibuktikan jika nilai akurasi, precision, recall, dan f1 score saling linear.

Model Awal kami adalah Adaboost karena jika dilihat secara akurasi dan LC memiliki performa yang paling baik. Namun, setelah dilakukan hyperparameter tuning, model Decision Tree memiliki performa yang lebih baik terutama dalam Learning Curve yang merupakan salah satu kriteria untuk melihat model termasuk overfitting atau underfitting. Karena kami berfikir jika hanya melihat akurasi saja tidak cukup untuk menilai model yang baik. Oleh karena itu, kami memilih model Decision Tree Classifier sebagai model final kami. Selisih akurasi antara model Adaboost dan Decision Tree Classifier tidak terlalu jauh hanya berkisar 0.01294, namun model Decision Tree Classifier lebih stabil dan tidak overfitting. LC pada model Decision Tree Classifier juga lebih stabil karena Training Score dan Cross Validation Score linear. Garis Validation Score juga mengikuti garis Training Score. Gap antara Training Score dan Cross Validation Score juga tidak terlalu jauh berkisar 0.2, Sedangkan gap Training-Validation mdoel Adabost mencapai 0.5. Jadi dengan berbagai pertimbangan tersebut, kami memilih model Decision Tree Classifier sebagai model final kami.

In [7]:
import pandas as pd

# Membuat dataframes
train_data = {
    "Model": ["Xgboost", "AdaBoost", "DecisionTree"],
    "Accuracy Train": [0.96271, 0.96327, 0.93450],
    "Precision Train": [0.99337, 0.99342, 0.98725],
    "Recall Train": [0.97117, 0.97212, 0.94767],
    "F1 Score Train": [0.98189, 0.98234, 0.96673]
}

val_data = {
    "Model": ["Xgboost", "AdaBoost", "DecisionTree"],
    "Accuracy Validation": [0.90268, 0.89844, 0.89121],
    "Precision Validation": [0.96183, 0.96263, 0.94664],
    "Recall Validation": [0.91775, 0.91389, 0.91248],
    "F1 Score Validation": [0.93814, 0.93639, 0.92825]
}

train_df = pd.DataFrame(train_data)
val_df = pd.DataFrame(val_data)

# Simpan ke Excel tanpa membulatkan
train_df.to_csv('model_performanceTrain.csv', index=False, float_format="%.5f")
val_df.to_csv('model_performanceTest.csv', index=False, float_format="%.5f")

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/BimaBayuUWUUU/DSAI_Batch6_Code/main/Finpro/data_FP/data_outliers/Cclean_outliers.csv')

In [3]:
print("Data sebelum menghapus duplikat:")
data

Data sebelum menghapus duplikat:

,id_pekerjaan,id_perusahaan,judul,gaji_rata-rata_perbulan,periode_pembayaran,jenis_pekerjaan_terformat,lamaran,diperbolehkan_jarak_jauh,tipe_pendaftaran,tingkat_pengalaman_terformat,...,mata_uang,tipe_kompensasi,id_industri,skill_1,skill_2,skill_3,nama_industri,nama_perusahaan,negara,jumlah_karyawan
0,3757940104,553718.0,Hearing Care Provider,5250.000000,MONTHLY,Full-time,0.0,0.0,OffsiteApply,Entry level,...,USD,BASE_SALARY,17.0,OTHR,NOT,NOT,Medical Equipment Manufacturing,HearingLife,US,1171.0
1,3757940025,2192142.0,Shipping & Receiving Associate 2nd shift (Beav...,7085.416667,YEARLY,Full-time,0.0,0.0,OffsiteApply,Mid-Senior level,...,USD,BASE_SALARY,135.0,MGMT,MNFC,NOT,Industrial Machinery Manufacturing,"Metalcraft of Mayville, Inc.",US,300.0
2,3757938019,474443.0,"Manager, Engineering",6776.000000,YEARLY,Full-time,0.0,0.0,OffsiteApply,Mid-Senior level,...,USD,BASE_SALARY,147.0,ENG,NOT,NOT,Automation Machinery Manufacturing,"U.S. Tsubaki Power Transmission, LLC",US,314.0
3,3757938018,18213359.0,Cook,3919.520000,HOURLY,Full-time,0.0,0.0,OffsiteApply,Entry level,...,USD,BASE_SALARY,100.0,MGMT,MNFC,NOT,Non-profit Organizations,Episcopal Communities & Services,US,36.0
4,3757937095,437225.0,Principal Cloud Security Architect (Remote),14791.666667,YEARLY,Full-time,0.0,1.0,OffsiteApply,Mid-Senior level,...,USD,BASE_SALARY,27.0,IT,NOT,NOT,Retail,"iHerb, LLC",US,1260.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39764,133196985,1089558.0,Model Risk Auditor,7500.000000,HOURLY,Contract,1.0,0.0,ComplexOnsiteApply,Mid-Senior level,...,USD,BASE_SALARY,104.0,ACCT,FIN,NOT,Staffing and Recruiting,Employvision Inc.,US,50.0
39765,133114754,77766802.0,Sales Manager,5632.000000,YEARLY,Full-time,0.0,0.0,ComplexOnsiteApply,Entry level,...,USD,BASE_SALARY,92.0,SALE,BD,NOT,Truck Transportation,CargoLogin.,US,15.0
39766,108965123,0.0,Office Administrative Assistant,4583.333333,YEARLY,Full-time,2.0,0.0,ComplexOnsiteApply,Mid-Senior level,...,USD,BASE_SALARY,19.0,ADM,NOT,NOT,Retail Apparel and Fashion,Unknown,Unknown,0.0
39767,102339515,52132271.0,Franchise Owner,5479.166667,YEARLY,Full-time,0.0,0.0,SimpleOnsiteApply,Mid-Senior level,...,USD,BASE_SALARY,91.0,BD,SALE,NOT,Consumer Services,DryerVentz - DuctVentz,US,7.0
39768,85008768,0.0,Licensed Insurance Agent,4073.333333,YEARLY,Full-time,0.0,0.0,ComplexOnsiteApply,Mid-Senior level,...,USD,BASE_SALARY,42.0,SALE,BD,NOT,Insurance,Unknown,Unknown,0.0

In [4]:
# Menghapus duplikat berdasarkan kolom 'id_pekerjaan'
data_cleaned = data.drop_duplicates(subset=['id_pekerjaan'])

print("\nData setelah menghapus duplikat:")
data_cleaned.sort_values(by='id_pekerjaan')

Data setelah menghapus duplikat:

,id_pekerjaan,id_perusahaan,judul,gaji_rata-rata_perbulan,periode_pembayaran,jenis_pekerjaan_terformat,lamaran,diperbolehkan_jarak_jauh,tipe_pendaftaran,tingkat_pengalaman_terformat,...,mata_uang,tipe_kompensasi,id_industri,skill_1,skill_2,skill_3,nama_industri,nama_perusahaan,negara,jumlah_karyawan
39768,85008768,0.0,Licensed Insurance Agent,4073.333333,YEARLY,Full-time,0.0,0.0,ComplexOnsiteApply,Mid-Senior level,...,USD,BASE_SALARY,42.0,SALE,BD,NOT,Insurance,Unknown,Unknown,0.0
39767,102339515,52132271.0,Franchise Owner,5479.166667,YEARLY,Full-time,0.0,0.0,SimpleOnsiteApply,Mid-Senior level,...,USD,BASE_SALARY,91.0,BD,SALE,NOT,Consumer Services,DryerVentz - DuctVentz,US,7.0
39766,108965123,0.0,Office Administrative Assistant,4583.333333,YEARLY,Full-time,2.0,0.0,ComplexOnsiteApply,Mid-Senior level,...,USD,BASE_SALARY,19.0,ADM,NOT,NOT,Retail Apparel and Fashion,Unknown,Unknown,0.0
39765,133114754,77766802.0,Sales Manager,5632.000000,YEARLY,Full-time,0.0,0.0,ComplexOnsiteApply,Entry level,...,USD,BASE_SALARY,92.0,SALE,BD,NOT,Truck Transportation,CargoLogin.,US,15.0
39764,133196985,1089558.0,Model Risk Auditor,7500.000000,HOURLY,Contract,1.0,0.0,ComplexOnsiteApply,Mid-Senior level,...,USD,BASE_SALARY,104.0,ACCT,FIN,NOT,Staffing and Recruiting,Employvision Inc.,US,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,3757937095,437225.0,Principal Cloud Security Architect (Remote),14791.666667,YEARLY,Full-time,0.0,1.0,OffsiteApply,Mid-Senior level,...,USD,BASE_SALARY,27.0,IT,NOT,NOT,Retail,"iHerb, LLC",US,1260.0
3,3757938018,18213359.0,Cook,3919.520000,HOURLY,Full-time,0.0,0.0,OffsiteApply,Entry level,...,USD,BASE_SALARY,100.0,MGMT,MNFC,NOT,Non-profit Organizations,Episcopal Communities & Services,US,36.0
2,3757938019,474443.0,"Manager, Engineering",6776.000000,YEARLY,Full-time,0.0,0.0,OffsiteApply,Mid-Senior level,...,USD,BASE_SALARY,147.0,ENG,NOT,NOT,Automation Machinery Manufacturing,"U.S. Tsubaki Power Transmission, LLC",US,314.0
1,3757940025,2192142.0,Shipping & Receiving Associate 2nd shift (Beav...,7085.416667,YEARLY,Full-time,0.0,0.0,OffsiteApply,Mid-Senior level,...,USD,BASE_SALARY,135.0,MGMT,MNFC,NOT,Industrial Machinery Manufacturing,"Metalcraft of Mayville, Inc.",US,300.0
0,3757940104,553718.0,Hearing Care Provider,5250.000000,MONTHLY,Full-time,0.0,0.0,OffsiteApply,Entry level,...,USD,BASE_SALARY,17.0,OTHR,NOT,NOT,Medical Equipment Manufacturing,HearingLife,US,1171.0

In [6]:
# data.to_csv('data_cleaned.csv', index=False)

# Coba 2

In [229]:
import joblib

# 1. Load trained model
# Assuming your trained model is saved as 'trained_model.pkl'
model5 = joblib.load('../Finpro/model/Xgb_model.pkl')
# Memuat kembali scaler dari file
loaded_scaler5 = joblib.load('../Finpro/model/scaler7.pkl')

In [230]:
import pandas as pd

In [233]:
data = {
    'diperbolehkan_jarak_jauh': [0],
    'periode_pembayaran_encoded': [4],
    'tingkat_pengalaman_terformat_encoded': [2],
    'tipe_pendaftaran_encoded': [3],
    'jenis_pekerjaan_Contract': [0],
    'jenis_pekerjaan_Full-time': [1],
    'jenis_pekerjaan_Internship': [0],
    'jenis_pekerjaan_Other': [0],
    'jenis_pekerjaan_Part-time': [0],
    'jenis_pekerjaan_Temporary': [0],
    'jenis_pekerjaan_Volunteer': [0],
    'jumlah_skill_perindustri': [2],
    'standar_gaji': [10000],
    'kategori_lamaran_industri': [2],
    'skill_Accounting/Auditing': [0],
    'skill_Administrative': [0],
    'skill_Advertising': [0],
    'skill_Analyst': [0],
    'skill_Art/Creative': [0],
    'skill_Business Development': [0],
    'skill_Consulting': [0],
    'skill_Customer Service': [0],
    'skill_Design': [0],
    'skill_Distribution': [0],
    'skill_Education': [0],
    'skill_Engineering': [1],
    'skill_Finance': [0],
    'skill_General Business': [0],
    'skill_Health Care Provider': [0],
    'skill_Human Resources': [0],
    'skill_Information Technology': [1],
    'skill_Legal': [0],
    'skill_Management': [0],
    'skill_Manufacturing': [0],
    'skill_Marketing': [0],
    'skill_Other': [0],
    'skill_Product Management': [0],
    'skill_Production': [0],
    'skill_Project Management': [0],
    'skill_Public Relations': [0],
    'skill_Purchasing': [0],
    'skill_Quality Assurance': [0],
    'skill_Research': [0],
    'skill_Sales': [0],
    'skill_Science': [0],
    'skill_Strategy/Planning': [0],
    'skill_Supply Chain': [0],
    'skill_Training': [0],
    'skill_Writing/Editing': [0],
    'sector_Construction and Engineering': [0],
    'sector_Consumer Services and Retail': [0],
    'sector_Education and Research': [0],
    'sector_Energy and Natural Resources': [0],
    'sector_Entertainment': [0],
    'sector_Finance and Legal Services': [0],
    'sector_Health and Wellness': [0],
    'sector_Manufacturing': [0],
    'sector_Non-profit and Government': [0],
    'sector_Professional and Business Services': [0],
    'sector_Technology and IT': [1],
    'sector_Transportation and Logistics': [0],
}

user_data =pd.DataFrame(data)

In [234]:
user_dataS = loaded_scaler5.transform(user_data)

In [235]:
user_dataS

array([[-0.29959564, -0.12823889, -1.22120084,  1.52621417, -0.22337217,
         0.44145042, -0.06476715, -0.04608036, -0.18628763, -0.06954285,
        -0.03113807,  0.17134587,  1.12963509,  0.0489142 , -0.24153124,
        -0.16629556, -0.18269122, -0.21286315, -0.15964029, -0.35530279,
        -0.195403  , -0.22847853, -0.17812964, -0.12484427, -0.20665016,
         2.70891362, -0.29543659, -0.21200712, -0.27412705, -0.18663528,
         2.44207774, -0.2093429 , -0.4444817 , -0.42285298, -0.24209223,
        -0.32476838, -0.15934094, -0.13943043, -0.21185117, -0.16416885,
        -0.15032106, -0.15924104, -0.18559065, -0.43018944, -0.14766752,
        -0.15375973, -0.1620172 , -0.18153798, -0.16132719, -0.25038973,
        -0.42652727, -0.30732863, -0.28333479, -0.2189297 , -0.35611275,
        -0.31377359, -0.54362617, -0.18207104, -0.2605419 ,  3.15320413,
        -0.25707995]])

In [236]:
# 4. Make prediction
prediction5 = model5.predict(user_dataS)

# 5. Print the prediction
print("Prediksi Pekerjaan:", prediction5)

Prediksi Pekerjaan: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 0.]]

In [237]:
import numpy as np

In [238]:
# Menemukan indeks dari nilai True
true_indices5 = np.where(prediction5[0])[0]

# Menampilkan indeks True
print("True ada pada indeks:", true_indices5+1)

True ada pada indeks: [64 67]

# Coba

In [1]:
import pandas as pd
import numpy as np

## Input

In [3]:
import joblib

# 1. Load trained model
# Assuming your trained model is saved as 'trained_model.pkl'
model = joblib.load('../Finpro/model/Dt4_model.pkl')
# Memuat kembali scaler dari file
loaded_scaler = joblib.load('../Finpro/model/scaler4.pkl')

In [24]:
# 1. Load trained model
# Assuming your trained model is saved as 'trained_model.pkl'
model2 = joblib.load('../Finpro/model/Dt_model.pkl')
# Memuat kembali scaler dari file
loaded_scaler2 = joblib.load('../Finpro/model/scaler3.pkl')

In [132]:
mapping_encoders = {
    'periode_pembayaran':{'MONTHLY':4, 'YEARLY':5, 'HOURLY':2, 'NOTPAID':1, 'WEEKLY':3},
    'tingkat_pengalaman_terformat': {'Entry level':2, 'Mid-Senior level': 4, 'Director':6, 'Associate':3,
       'Executive': 5, 'Internship':1},
    'tipe_pendaftaran': {'OffsiteApply':1, 'SimpleOnsiteApply':2, 'ComplexOnsiteApply':3},
    'skill_1': {'PRCH':1,'SUPL':2,'PR':3,'SCI':4,'STRA':5,'WRT':6,'QA':7,'DIST':8,'PROD':9,
                'PRJM':10,'ADVR':11,'RSCH':12,'HR':13,'LGL':14,'PRDM':15,'MRKT':16,'EDU':17,'TRNG':18,
                'ANLS':19,'FIN':20,'SALE':21,'BD':22,'MGMT':23,'MNFC':24,'GENB':25,'CUST':26,'ENG':27,
                'OTHR':28,'CNSL':29,'ACCT':30,'HCPR':31,'DSGN':32,'ART':33,'IT':34,'ADM':35, 'NOT':36},
    'skill_2': {'PRCH':1,'SUPL':2,'PR':3,'SCI':4,'STRA':5,'WRT':6,'QA':7,'DIST':8,'PROD':9,
                'PRJM':10,'ADVR':11,'RSCH':12,'HR':13,'LGL':14,'PRDM':15,'MRKT':16,'EDU':17,'TRNG':18,
                'ANLS':19,'FIN':20,'SALE':21,'BD':22,'MGMT':23,'MNFC':24,'GENB':25,'CUST':26,'ENG':27,
                'OTHR':28,'CNSL':29,'ACCT':30,'HCPR':31,'DSGN':32,'ART':33,'IT':34,'ADM':35,'NOT':36},
    'skill_3': {'PRCH':1,'SUPL':2,'PR':3,'SCI':4,'STRA':5,'WRT':6,'QA':7,'DIST':8,'PROD':9,
                'PRJM':10,'ADVR':11,'RSCH':12,'HR':13,'LGL':14,'PRDM':15,'MRKT':16,'EDU':17,'TRNG':18,
                'ANLS':19,'FIN':20,'SALE':21,'BD':22,'MGMT':23,'MNFC':24,'GENB':25,'CUST':26,'ENG':27,
                'OTHR':28,'CNSL':29,'ACCT':30,'HCPR':31,'DSGN':32,'ART':33,'IT':34,'ADM':35,'NOT':36},
}

In [ ]:
{'Finance and Legal Services': 4, 'Manufacturing': 8, 'Technology and IT': 11, 'Health and Wellness': 6, 'Education and Research': 3, 'Construction and Engineering': 1, 'Consumer Services and Retail': 2, 'Transportation and Logistics': 12, 'Energy and Natural Resources': 5, 'Professional and Business Services': 10, 'Non-profit and Government': 9, 'Entertainment Providers': 7}

In [38]:
def get_user_input():
    print("Masukkan data untuk prediksi:")
    diperbolehkan_jarak_jauh = int(input("Apakah diperbolehkan jarak jauh? (0 untuk tidak, 1 untuk ya): "))
    periode_pembayaran_encoded = int(input("Masukkan periode pembayaran (encoded): "))
    tingkat_pengalaman_terformat_encoded = int(input("Masukkan tingkat pengalaman terformat (encoded): "))
    tipe_pendaftaran_encoded = int(input("Masukkan tipe pendaftaran (encoded): "))
    jenis_pekerjaan_Contract = int(input("Apakah jenis pekerjaan adalah Contract? (0 untuk tidak, 1 untuk ya): "))
    jenis_pekerjaan_Full_time = int(input("Apakah jenis pekerjaan adalah Full-time? (0 untuk tidak, 1 untuk ya): "))
    jenis_pekerjaan_Internship = int(input("Apakah jenis pekerjaan adalah Internship? (0 untuk tidak, 1 untuk ya): "))
    jenis_pekerjaan_Other = int(input("Apakah jenis pekerjaan adalah Other? (0 untuk tidak, 1 untuk ya): "))
    jenis_pekerjaan_Part_time = int(input("Apakah jenis pekerjaan adalah Part-time? (0 untuk tidak, 1 untuk ya): "))
    jenis_pekerjaan_Temporary = int(input("Apakah jenis pekerjaan adalah Temporary? (0 untuk tidak, 1 untuk ya): "))
    jenis_pekerjaan_Volunteer = int(input("Apakah jenis pekerjaan adalah Volunteer? (0 untuk tidak, 1 untuk ya): "))
    jumlah_skill_perindustri = int(input("Masukkan jumlah skill per industri: "))
    standar_gaji = float(input("Masukkan standar gaji: "))
    kategori_lamaran_industri = int(input("Masukkan kategori lamaran industri: "))
    skill_1 = int(input("Masukkan skill 1 (encoded): "))
    skill_2 = int(input("Masukkan skill 2 (encoded): "))
    skill_3 = int(input("Masukkan skill 3 (encoded): "))
    sector_encoded = int(input("Masukkan sektor industri (encoded): "))

    # Buat DataFrame dengan input dari pengguna
    user_input = pd.DataFrame({
        'diperbolehkan_jarak_jauh': [diperbolehkan_jarak_jauh],
        'periode_pembayaran_encoded': [periode_pembayaran_encoded],
        'tingkat_pengalaman_terformat_encoded': [tingkat_pengalaman_terformat_encoded],
        'tipe_pendaftaran_encoded': [tipe_pendaftaran_encoded],
        'jenis_pekerjaan_Contract': [jenis_pekerjaan_Contract],
        'jenis_pekerjaan_Full-time': [jenis_pekerjaan_Full_time],
        'jenis_pekerjaan_Internship': [jenis_pekerjaan_Internship],
        'jenis_pekerjaan_Other': [jenis_pekerjaan_Other],
        'jenis_pekerjaan_Part-time': [jenis_pekerjaan_Part_time],
        'jenis_pekerjaan_Temporary': [jenis_pekerjaan_Temporary],
        'jenis_pekerjaan_Volunteer': [jenis_pekerjaan_Volunteer],
        'jumlah_skill_perindustri': [jumlah_skill_perindustri],
        'standar_gaji': [standar_gaji],
        'kategori_lamaran_industri': [kategori_lamaran_industri],
        'skill_1': [skill_1],
        'skill_2': [skill_2],
        'skill_3': [skill_3],
        'sector_encoded': [sector_encoded]
    })

    return user_input

In [63]:
# 3. Get user input
# Membuat DataFrame
data = {
    'diperbolehkan_jarak_jauh': [0],
    'periode_pembayaran_encoded': [4],
    'tingkat_pengalaman_terformat_encoded': [2],
    'tipe_pendaftaran_encoded': [3],
    'jenis_pekerjaan_Contract': [0],
    'jenis_pekerjaan_Full-time': [1],
    'jenis_pekerjaan_Internship': [0],
    'jenis_pekerjaan_Other': [0],
    'jenis_pekerjaan_Part-time': [0],
    'jenis_pekerjaan_Temporary': [0],
    'jenis_pekerjaan_Volunteer': [0],
    'jumlah_skill_perindustri': [2],
    'standar_gaji': [9000.0],
    'kategori_lamaran_industri': [2],
    'skill_1': [30],
    'skill_2': [22],
    'skill_3': [21],
    'sector_encoded': [4]
}

user_data =pd.DataFrame(data)

In [266]:
user_data

,diperbolehkan_jarak_jauh,periode_pembayaran_encoded,tingkat_pengalaman_terformat_encoded,tipe_pendaftaran_encoded,jenis_pekerjaan_Contract,jenis_pekerjaan_Full-time,jenis_pekerjaan_Internship,jenis_pekerjaan_Other,jenis_pekerjaan_Part-time,jenis_pekerjaan_Temporary,jenis_pekerjaan_Volunteer,jumlah_skill_perindustri,standar_gaji,kategori_lamaran_industri,skill_1,skill_2,skill_3,sector_encoded
0,0,4,2,2,0,1,0,0,0,0,0,2,10000.0,1,34,27,0,11

In [64]:
userdata4 = user_data.drop(columns=['sector_encoded'])

In [65]:
user_dataS = loaded_scaler.transform(userdata4)

In [66]:
user_dataS

array([[-0.29959564, -0.12823889, -1.22120084,  1.52621417, -0.22337217,
         0.44145042, -0.06476715, -0.04608036, -0.18628763, -0.06954285,
        -0.03113807,  0.17134587,  0.68804657,  0.0489142 ,  0.86122977,
        -0.59150858, -0.61907217]])

In [67]:
# 4. Make prediction
prediction = model.predict(user_dataS)

# 5. Print the prediction
print("Prediksi Pekerjaan:", prediction)

Prediksi Pekerjaan: [[False False False False False False False False False False False False
   True False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False]]

In [68]:
# Menemukan indeks dari nilai True
true_indices = np.where(prediction[0])[0]

# Menampilkan indeks True
print("True ada pada indeks:", true_indices+1)

True ada pada indeks: [13]

In [69]:
user_dataS2 = loaded_scaler2.transform(user_data)

In [70]:
user_dataS2

array([[-0.29959564, -0.12823889, -1.22120084,  1.52621417, -0.22337217,
         0.44145042, -0.06476715, -0.04608036, -0.18628763, -0.06954285,
        -0.03113807,  0.17134587,  0.68804657,  0.0489142 ,  0.86122977,
        -0.59150858, -0.61907217, -0.76304632]])

In [71]:
# 4. Make prediction
prediction2 = model2.predict(user_dataS2)

# 5. Print the prediction
print("Prediksi Pekerjaan:", prediction2)

Prediksi Pekerjaan: [[False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False  True False False False False False False False  True False False
  False False False False False False False False False False False False
  False  True False]]

In [72]:
# Menemukan indeks dari nilai True
true_indices2 = np.where(prediction2[0])[0]

# Menampilkan indeks True
print("True ada pada indeks:", true_indices2+1)

True ada pada indeks: [50 58 74]

In [129]:
mapping_industri = {
    1: 'Accounting', 
    2: 'Advertising Services', 
    3: 'Airlines and Aviation',
    4: 'Appliances, Electrical, and Electronics Manufacturing',
    5: 'Architecture and Planning',
    6: 'Automation Machinery Manufacturing',
    7: 'Aviation and Aerospace Component Manufacturing',
    8: 'Banking',
    9: 'Biotechnology Research',
    10: 'Book and Periodical Publishing',
    11: 'Broadcast Media Production and Distribution',
    12: 'Business Consulting and Services',
    13: 'Chemical Manufacturing',
    14: 'Civil Engineering',
    15: 'Computer Hardware Manufacturing',
    16: 'Computer and Network Security',
    17: 'Computers and Electronics Manufacturing',
    18: 'Construction',
    19: 'Consumer Services',
    20: 'Defense and Space Manufacturing',
    21: 'Design Services',
    22: 'E-Learning Providers',
    23: 'Education Administration Programs',
    24: 'Entertainment Providers',
    25: 'Environmental Services',
    26: 'Facilities Services',
    27: 'Financial Services',
    28: 'Food and Beverage Manufacturing',
    29: 'Food and Beverage Services',
    30: 'Government Administration',
    31: 'Higher Education',
    32: 'Hospitality',
    33: 'Hospitals and Health Care',
    34: 'Human Resources Services',
    35: 'IT Services and IT Consulting',
    36: 'Individual and Family Services',
    37: 'Industrial Machinery Manufacturing',
    38: 'Information Services',
    39: 'Insurance',
    40: 'Internet Marketplace Platforms',
    41: 'Investment Banking',
    42: 'Investment Management',
    43: 'Law Practice',
    44: 'Legal Services',
    45: 'Machinery Manufacturing',
    46: 'Manufacturing',
    47: 'Medical Equipment Manufacturing',
    48: 'Medical Practices',
    49: 'Mental Health Care',
    50: 'Mining',
    51: 'Motor Vehicle Manufacturing',
    52: 'Non-profit Organizations',
    53: 'Oil and Gas',
    54: 'Packaging and Containers Manufacturing',
    55: 'Pharmaceutical Manufacturing',
    56: 'Primary and Secondary Education',
    57: 'Real Estate',
    58: 'Renewable Energy Semiconductor Manufacturing',
    59: 'Research Services',
    60: 'Restaurants',
    61: 'Retail',
    62: 'Retail Apparel and Fashion',
    63: 'Semiconductor Manufacturing',
    64: 'Software Development',
    65: 'Staffing and Recruiting',
    66: 'Technology, Information and Internet',
    67: 'Telecommunications',
    68: 'Transportation, Logistics, Supply Chain and Storage',
    69: 'Travel Arrangements',
    70: 'Truck Transportation',
    71: 'Utilities',
    72: 'Veterinary Services',
    73: 'Wellness and Fitness Services',
    74: 'Wholesale',
    75: 'Wholesale Building Materials'
}

# NLP

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from nltk.corpus import stopwords
import nltk

# Download stopwords
nltk.download('stopwords')

# Data
mapping_industri = {
    1: 'Accounting',
    2: 'Advertising Services',
    3: 'Airlines and Aviation',
    4: 'Appliances, Electrical, and Electronics Manufacturing',
    5: 'Architecture and Planning',
    6: 'Automation Machinery Manufacturing',
    7: 'Aviation and Aerospace Component Manufacturing',
    8: 'Banking',
    9: 'Biotechnology Research',
    10: 'Book and Periodical Publishing',
    11: 'Broadcast Media Production and Distribution',
    12: 'Business Consulting and Services',
    13: 'Chemical Manufacturing',
    14: 'Civil Engineering',
    15: 'Computer Hardware Manufacturing',
    16: 'Computer and Network Security',
    17: 'Computers and Electronics Manufacturing',
    18: 'Construction',
    19: 'Consumer Services',
    20: 'Defense and Space Manufacturing',
    21: 'Design Services',
    22: 'E-Learning Providers',
    23: 'Education Administration Programs',
    24: 'Entertainment Providers',
    25: 'Environmental Services',
    26: 'Facilities Services',
    27: 'Financial Services',
    28: 'Food and Beverage Manufacturing',
    29: 'Food and Beverage Services',
    30: 'Government Administration',
    31: 'Higher Education',
    32: 'Hospitality',
    33: 'Hospitals and Health Care',
    34: 'Human Resources Services',
    35: 'IT Services and IT Consulting',
    36: 'Individual and Family Services',
    37: 'Industrial Machinery Manufacturing',
    38: 'Information Services',
    39: 'Insurance',
    40: 'Internet Marketplace Platforms',
    41: 'Investment Banking',
    42: 'Investment Management',
    43: 'Law Practice',
    44: 'Legal Services',
    45: 'Machinery Manufacturing',
    46: 'Manufacturing',
    47: 'Medical Equipment Manufacturing',
    48: 'Medical Practices',
    49: 'Mental Health Care',
    50: 'Mining',
    51: 'Motor Vehicle Manufacturing',
    52: 'Non-profit Organizations',
    53: 'Oil and Gas',
    54: 'Packaging and Containers Manufacturing',
    55: 'Pharmaceutical Manufacturing',
    56: 'Primary and Secondary Education',
    57: 'Real Estate',
    58: 'Renewable Energy Semiconductor Manufacturing',
    59: 'Research Services',
    60: 'Restaurants',
    61: 'Retail',
    62: 'Retail Apparel and Fashion',
    63: 'Semiconductor Manufacturing',
    64: 'Software Development',
    65: 'Staffing and Recruiting',
    66: 'Technology, Information and Internet',
    67: 'Telecommunications',
    68: 'Transportation, Logistics, Supply Chain and Storage',
    69: 'Travel Arrangements',
    70: 'Truck Transportation',
    71: 'Utilities',
    72: 'Veterinary Services',
    73: 'Wellness and Fitness Services',
    74: 'Wholesale',
    75: 'Wholesale Building Materials'
}

# Membuat dataframe dari mapping industri
df = pd.DataFrame(list(mapping_industri.items()), columns=['industry_id', 'industry_description'])

print(df.head())

   industry_id                               industry_description
0            1                                         Accounting
1            2                               Advertising Services
2            3                              Airlines and Aviation
3            4  Appliances, Electrical, and Electronics Manufa...
4            5                          Architecture and Planning

[nltk_data] Downloading package stopwords to C:\Users\HP
[nltk_data]     Pavilion\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
# Menghilangkan stopwords dan membuat representasi TF-IDF
stop_words = stopwords.words('english')
vectorizer = TfidfVectorizer(stop_words=stop_words)
X = vectorizer.fit_transform(df['industry_description'])

print(X.shape)  # Melihat ukuran matriks TF-IDF

(75, 119)

In [3]:
# Clustering menggunakan K-Means
kmeans = KMeans(n_clusters=10, random_state=42)
df['cluster'] = kmeans.fit_predict(X)

print(df.head())

   industry_id                               industry_description  cluster
0            1                                         Accounting        0
1            2                               Advertising Services        6
2            3                              Airlines and Aviation        8
3            4  Appliances, Electrical, and Electronics Manufa...        2
4            5                          Architecture and Planning        0

In [4]:
# Melihat deskripsi industri dalam setiap cluster
for cluster in sorted(df['cluster'].unique()):
    print(f"Cluster {cluster}:")
    print(df[df['cluster'] == cluster]['industry_description'].values)
    print("\n")

Cluster 0:
['Accounting' 'Architecture and Planning' 'Biotechnology Research'
 'Book and Periodical Publishing'
 'Broadcast Media Production and Distribution' 'Civil Engineering'
 'Computer and Network Security' 'Construction'
 'Government Administration' 'Hospitality' 'Insurance'
 'Internet Marketplace Platforms' 'Law Practice' 'Mining'
 'Non-profit Organizations' 'Oil and Gas' 'Real Estate' 'Restaurants'
 'Retail' 'Retail Apparel and Fashion' 'Software Development'
 'Staffing and Recruiting' 'Technology, Information and Internet'
 'Telecommunications'
 'Transportation, Logistics, Supply Chain and Storage'
 'Travel Arrangements' 'Truck Transportation' 'Utilities']


Cluster 1:
['Medical Equipment Manufacturing' 'Medical Practices']


Cluster 2:
['Appliances, Electrical, and Electronics Manufacturing'
 'Automation Machinery Manufacturing' 'Chemical Manufacturing'
 'Computer Hardware Manufacturing'
 'Computers and Electronics Manufacturing'
 'Defense and Space Manufacturing' 'Food and Beverage Manufacturing'
 'Industrial Machinery Manufacturing' 'Machinery Manufacturing'
 'Manufacturing' 'Motor Vehicle Manufacturing'
 'Packaging and Containers Manufacturing' 'Pharmaceutical Manufacturing'
 'Renewable Energy Semiconductor Manufacturing'
 'Semiconductor Manufacturing']


Cluster 3:
['Education Administration Programs' 'Higher Education'
 'Primary and Secondary Education']


Cluster 4:
['E-Learning Providers' 'Entertainment Providers']


Cluster 5:
['Banking' 'Investment Banking' 'Investment Management']


Cluster 6:
['Advertising Services' 'Business Consulting and Services'
 'Consumer Services' 'Design Services' 'Environmental Services'
 'Facilities Services' 'Financial Services' 'Food and Beverage Services'
 'Human Resources Services' 'IT Services and IT Consulting'
 'Individual and Family Services' 'Information Services' 'Legal Services'
 'Research Services' 'Veterinary Services' 'Wellness and Fitness Services']


Cluster 7:
['Hospitals and Health Care' 'Mental Health Care']


Cluster 8:
['Airlines and Aviation' 'Aviation and Aerospace Component Manufacturing']


Cluster 9:
['Wholesale' 'Wholesale Building Materials']